# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reseau',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('input', models.IntegerField(default=0)),
            ],
        ),
    ]
