# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Reseau',
        ),
    ]
