# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_info',
            field=models.CharField(default='allo', max_length=500),
            preserve_default=False,
        ),
    ]
