# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_game_game_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_info',
            field=models.CharField(default=b'allo', max_length=500),
        ),
    ]
