# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20170310_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_info',
            new_name='game_inform',
        ),
    ]
