# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20170310_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_info',
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
