# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_bestscore_score'),
        ('play', '0007_auto_20170310_1534'),
    ]

    operations = [
    ]
