# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-12 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestScore',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AlterField(
            model_name='game',
            name='info',
            field=models.CharField(default='', max_length=300),
        ),
    ]
