# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-12 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_auto_20170312_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=200)),
                ('best_score', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Game')),
            ],
        ),
    ]
