# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_auto_20170329_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseau',
            name='name',
        ),
        migrations.AddField(
            model_name='reseau',
            name='type',
            field=models.CharField(choices=[(b'MLP', b'MLP'), (b'Elman', b'Elman'), (b'Jordan', b'Jordan')], default=b'MLP', max_length=100),
        ),
        migrations.AlterField(
            model_name='reseau',
            name='defeat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reseau',
            name='victory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reseau',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
