# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0014_auto_20170330_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=b'saves/')),
            ],
        ),
    ]
