# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-31 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_auto_20170331_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseau_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(default=b'', max_length=100)),
                ('info', models.CharField(default=b'toto', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='reseau',
            name='type',
            field=models.CharField(choices=[(b'select_type', b'select'), (b'MLP', b'MLP'), (b'Elman', b'Elman'), (b'Jordan', b'Jordan')], default=b'select', max_length=100),
        ),
    ]
