# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-31 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0016_auto_20170331_0915'),
        ('play', '0015_save'),
    ]

    operations = [
    ]
