# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0018_auto_20170331_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
        migrations.RemoveField(
            model_name='reseau',
            name='info',
        ),
        migrations.AlterField(
            model_name='reseau',
            name='defeat',
            field=models.FloatField(blank=True, help_text='punishement for each lost game', null=True, verbose_name='defeat punishement'),
        ),
        migrations.AlterField(
            model_name='reseau',
            name='network_layers',
            field=models.CharField(blank=True, help_text='number of hidden layers for a given network, format: *,*,...,*, . Unexpecting behavior if incorrect form', max_length=16, null=True, verbose_name='hidden layers'),
        ),
        migrations.AlterField(
            model_name='reseau',
            name='type',
            field=models.CharField(choices=[('select_type', 'select'), ('mlp', 'MLP'), ('elman', 'Elman'), ('jordan', 'Jordan'), ('op_tempo', 'Temporizer'), ('op_plus', 'Add'), ('op_minus', 'Substract'), ('op_divide', 'Divide'), ('op_avg', 'Average'), ('op_recomp', 'Recomposite'), ('op_decomp', 'Decomposite')], default='select', help_text='type involving different behavior of your network', max_length=100),
        ),
        migrations.AlterField(
            model_name='reseau',
            name='victory',
            field=models.FloatField(blank=True, help_text='reward at each game won', null=True, verbose_name='victory reward'),
        ),
        migrations.AlterField(
            model_name='reseau',
            name='weight',
            field=models.FloatField(blank=True, help_text='weight influence for each iteration', null=True, verbose_name='weight scaling'),
        ),
        migrations.AlterField(
            model_name='reseau_info',
            name='info',
            field=models.CharField(default='toto', max_length=300),
        ),
        migrations.AlterField(
            model_name='reseau_info',
            name='network_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
