# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0020_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
