# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('item_title', models.CharField(max_length=200)),
                ('item_link', models.CharField(max_length=200)),
            ],
        ),
    ]
