# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
