# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronit', '0002_auto_20170310_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='item_link',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='item_title',
        ),
        migrations.AddField(
            model_name='carousel',
            name='intro_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='link_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
