# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuronit', '0003_auto_20170310_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
