# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neuronit', '0004_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('intro_text', models.CharField(max_length=500, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('link_text', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
