# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import neuronit.models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronit', '0005_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=neuronit.models.get_image_path),
        ),
    ]
