# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuronit', '0006_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='intro_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
