# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about-us', '0003_auto_20170324_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
