# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-24 10:46
from __future__ import unicode_literals

from ..models import *
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about-us', '0004_auto_20170324_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=get_image_path),
        ),
    ]
